# -*- coding: utf-8 -*-
"""01_structure_sql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-pIqO8ItlhOKezfNlywWGjVRJo8uZH6F

# Data Structuring & Granularity
### Boston Ride-Hailing Analysis · Q4 2018 (Nov–Dec)
**Uber as focal platform · Lyft as competitive benchmark**

> Queries written in BigQuery-compatible SQL, executed locally via DuckDB.  
> The SQL in this notebook is portable, it runs unchanged on BigQuery, Redshift, or Snowflake.

**What this notebook does:**
1. Loads the raw dataset into an in-process DuckDB database with explicit type casting
2. Profiles the schema: row counts, column types, distinct values
3. Defines what one row represents (granularity)
4. Segments the data into analytical views: platform, ride tier, geography, time
5. Surfaces structural data quality issues before cleaning begins
"""

import duckdb
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

con = duckdb.connect()
print("DuckDB version:", duckdb.__version__)
print("pandas version:", pd.__version__)

"""## 1) Load Raw Data into DuckDB

We load the CSV with all columns as VARCHAR first, then apply explicit `TRY_CAST` for numeric fields.  
This avoids DuckDB's auto-inference treating mixed-format columns as strings, a common issue with real-world ride data.

"""

# Load with all_varchar=true, then cast numerics explicitly
# TRY_CAST returns NULL on failure rather than raising an error, safe for dirty data

con.execute("""
    CREATE OR REPLACE VIEW rides_raw AS
    SELECT * REPLACE(
        TRY_CAST(price            AS DOUBLE) AS price,
        TRY_CAST(surge_multiplier AS DOUBLE) AS surge_multiplier,
        TRY_CAST(distance         AS DOUBLE) AS distance,
        TRY_CAST(temperature      AS DOUBLE) AS temperature,
        TRY_CAST(latitude         AS DOUBLE) AS latitude,
        TRY_CAST(longitude        AS DOUBLE) AS longitude,
        TRY_CAST("Driver Ratings" AS DOUBLE) AS "Driver Ratings",
        TRY_CAST("Customer Rating" AS DOUBLE) AS "Customer Rating"
    )
    FROM read_csv_auto('BOSTON_ride_bookings_FULL.csv', all_varchar=true, ignore_errors=true)
""")

row_count = con.execute("SELECT COUNT(*) AS total_rows FROM rides_raw").fetchdf()
print(row_count.to_string(index=False))

"""## 2) Schema Profiling

We inspect all 23 columns, their types post-casting, and which analytical category each belongs to.
"""

schema = con.execute("""
    SELECT
        column_name,
        data_type,
        CASE
            WHEN data_type IN ('VARCHAR', 'BLOB')              THEN 'categorical/text'
            WHEN data_type IN ('BIGINT', 'INTEGER', 'HUGEINT') THEN 'integer'
            WHEN data_type IN ('DOUBLE', 'FLOAT')              THEN 'numeric'
            ELSE data_type
        END AS type_class
    FROM information_schema.columns
    WHERE table_name = 'rides_raw'
    ORDER BY ordinal_position
""").fetchdf()

print(schema.to_string(index=False))

"""## 3) Granularity: What Does One Row Represent?

Establishing granularity is the first question in any data model. We verify each row is a unique ride booking, not a repeated price observation per route.

"""

granularity = con.execute("""
    SELECT
        COUNT(*)           AS total_rows,
        COUNT(DISTINCT id) AS distinct_ids,
        COUNT(*) - COUNT(DISTINCT id) AS duplicate_ids,
        CASE WHEN COUNT(*) = COUNT(DISTINCT id)
             THEN 'Confirmed: one row = one unique ride booking'
             ELSE 'WARNING: Duplicate IDs detected'
        END AS verdict
    FROM rides_raw
""").fetchdf()

print(granularity.to_string(index=False))

# Secondary check: can the same route + time + platform produce multiple rows?

route_dupes = con.execute("""
    SELECT source, destination, datetime, cab_type, name, COUNT(*) AS row_count
    FROM rides_raw
    GROUP BY source, destination, datetime, cab_type, name
    HAVING COUNT(*) > 1
    ORDER BY row_count DESC
    LIMIT 10
""").fetchdf()

if len(route_dupes) == 0:
    print("No duplicate route+time+platform combinations. Granularity confirmed.")
else:
    print(f"{len(route_dupes)} duplicate route/time combinations found:")
    print(route_dupes.to_string(index=False))

    print("\nNote: duplicates exist but represent a negligible share of total records (~0.001%).")
    print("Each has a unique ride_id; granularity holds at the row level.")
    print("Interpretation: same route booked by different riders at the same minute, not data errors.")

"""## 4.) Platform Segmentation: Uber vs. Lyft

The dataset covers two platforms. **Uber is our focal platform; Lyft serves as a competitive benchmark** throughout the analysis.
"""

platform_split = con.execute("""
    SELECT
        cab_type                                                   AS platform,
        COUNT(*)                                                   AS total_rides,
        ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 1)        AS pct_of_total,
        COUNT(DISTINCT name)                                       AS ride_products,
        ROUND(AVG(price), 2)                                       AS avg_price,
        ROUND(MIN(price), 2)                                       AS min_price,
        ROUND(MAX(price), 2)                                       AS max_price
    FROM rides_raw
    GROUP BY cab_type
    ORDER BY total_rides DESC
""").fetchdf()

print(platform_split.to_string(index=False))

print("\nNote: Lyft's average price ($17.35) exceeds Uber's ($15.80) at the platform level.")
print("\nThis reflects Lyft's product mix, no low-margin Taxi equivalent, and strong premium tier volume.")

"""## 5) Ride Tier Taxonomy

Each platform offers multiple service tiers; economy, standard, premium, shared, and accessible. We map all products and assign a consistent tier label used across all notebooks.

"""

ride_products = con.execute("""
    SELECT
        cab_type,
        name                                           AS product,
        COUNT(*)                                       AS rides,
        ROUND(AVG(price), 2)                           AS avg_price,
        ROUND(STDDEV(price), 2)                        AS price_stddev,
        COUNT(*) FILTER (WHERE price IS NULL)          AS price_nulls
    FROM rides_raw
    GROUP BY cab_type, name
    ORDER BY cab_type, avg_price NULLS LAST
""").fetchdf()

print(ride_products.to_string(index=False))

# Register tiered view — consistent tier labels used in all downstream notebooks

con.execute("""
    CREATE OR REPLACE VIEW rides_tiered AS
    SELECT *,
        CASE name
            WHEN 'UberPool'     THEN 'Economy'
            WHEN 'Shared'       THEN 'Economy'
            WHEN 'UberX'        THEN 'Standard'
            WHEN 'Lyft'         THEN 'Standard'
            WHEN 'UberXL'       THEN 'Standard-XL'
            WHEN 'Lyft XL'      THEN 'Standard-XL'
            WHEN 'Black'        THEN 'Premium'
            WHEN 'Lux'          THEN 'Premium'
            WHEN 'Lux Black'    THEN 'Premium'
            WHEN 'Black SUV'    THEN 'Premium-XL'
            WHEN 'Lux Black XL' THEN 'Premium-XL'
            WHEN 'WAV'          THEN 'Accessible'
            WHEN 'Taxi'         THEN 'Taxi'
            ELSE                     'Unknown'
        END AS ride_tier
    FROM rides_raw
""")

tier_summary = con.execute("""
    SELECT ride_tier, cab_type, COUNT(*) AS rides
    FROM rides_tiered
    GROUP BY ride_tier, cab_type
    ORDER BY ride_tier, cab_type
""").fetchdf()

print(tier_summary.to_string(index=False))

"""## 6) Geographic Structure: Neighborhoods & Corridors

The dataset covers 12 Boston neighborhoods as both origins and destinations, all within the city core. We enumerate all corridors and surface the highest-volume routes.

"""

neighborhoods = con.execute("""
    SELECT DISTINCT source AS neighborhood FROM rides_raw
    UNION
    SELECT DISTINCT destination FROM rides_raw
    ORDER BY neighborhood
""").fetchdf()

print(f"Unique neighborhoods: {len(neighborhoods)}\n")
print(neighborhoods.to_string(index=False))

top_corridors = con.execute("""
    SELECT
        source,
        destination,
        COUNT(*)                 AS total_rides,
        ROUND(AVG(price), 2)     AS avg_price,
        ROUND(AVG(distance), 3)  AS avg_distance_miles
    FROM rides_raw
    WHERE source != destination
    GROUP BY source, destination
    ORDER BY total_rides DESC
    LIMIT 15
""").fetchdf()

print("Top 15 corridors by volume:\n")
print(top_corridors.to_string(index=False))

print("\nNote: High-volume corridors are symmetric (e.g. Financial District ↔ South Station).")
print("This reflects the dataset's balanced sampling across all route directions.")

"""## 7) Temporal Structure

We confirm the coverage window and profile demand distribution across hours of the day. This dataset covers exactly Q4 2018: November and December.
"""

monthly = con.execute("""
    SELECT month, COUNT(*) AS rides, COUNT(DISTINCT day) AS unique_days
    FROM rides_raw
    GROUP BY month
    ORDER BY month
""").fetchdf()

print("Monthly coverage:\n")
print(monthly.to_string(index=False))

print("\nNote: December has more rides than November (406,614 vs 286,457) and more unique days")
print("captured (12 vs 5). This reflects uneven sampling across the two months, not")
print("a true demand difference. Time-series analysis should account for this imbalance.\n")

hourly = con.execute("""
    SELECT
        hour,
        COUNT(*) AS rides,
        ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS pct_of_total
    FROM rides_raw
    GROUP BY hour
    ORDER BY hour
""").fetchdf()

print("Hourly distribution:\n")
print(hourly.to_string(index=False))

"""## 8. Structural Null Audit

We profile missingness across all columns with sparse data, then diagnose whether each null pattern is **random** or **structural** (tied to a specific platform or product). This distinction drives every cleaning decision in Notebook 02.
"""

null_audit = con.execute("""
    SELECT 'price'            AS col, COUNT(*) FILTER (WHERE price IS NULL)             AS nulls, COUNT(*) AS total FROM rides_raw
    UNION ALL
    SELECT 'Payment Method',           COUNT(*) FILTER (WHERE "Payment Method" IS NULL),  COUNT(*) FROM rides_raw
    UNION ALL
    SELECT 'Vehicle Type',             COUNT(*) FILTER (WHERE "Vehicle Type" IS NULL),    COUNT(*) FROM rides_raw
    UNION ALL
    SELECT 'Driver Ratings',           COUNT(*) FILTER (WHERE "Driver Ratings" IS NULL),  COUNT(*) FROM rides_raw
    UNION ALL
    SELECT 'Customer Rating',          COUNT(*) FILTER (WHERE "Customer Rating" IS NULL), COUNT(*) FROM rides_raw
    UNION ALL
    SELECT 'surge_multiplier',         COUNT(*) FILTER (WHERE surge_multiplier IS NULL),  COUNT(*) FROM rides_raw
""").fetchdf()

null_audit['null_pct'] = (null_audit['nulls'] / null_audit['total'] * 100).round(1)
print(null_audit.to_string(index=False))

# Diagnosis 1: Are price nulls confined to Taxi?

price_dx = con.execute("""
    SELECT
        name, cab_type, COUNT(*) AS total,
        COUNT(*) FILTER (WHERE price IS NULL) AS price_nulls,
        ROUND(COUNT(*) FILTER (WHERE price IS NULL) * 100.0 / COUNT(*), 1) AS pct_null
    FROM rides_raw
    GROUP BY name, cab_type
    ORDER BY price_nulls DESC
""").fetchdf()

print("Price null breakdown by product:\n")
print(price_dx.to_string(index=False))

print("\nFinding: All 55,095 price nulls are exclusively in the 'Taxi' product.")
print("Structural null: Taxi fare was not collected in this dataset.")
print("Decision → Notebook 02 (Data Cleaning): Exclude Taxi from price analysis. Retain as separate segment.")

# Diagnosis 2: Are Payment Method nulls platform-specific?

payment_dx = con.execute("""
    SELECT
        cab_type,
        COUNT(*) AS total,
        COUNT(*) FILTER (WHERE "Payment Method" IS NULL) AS payment_nulls,
        ROUND(COUNT(*) FILTER (WHERE "Payment Method" IS NULL) * 100.0 / COUNT(*), 1) AS pct_null
    FROM rides_raw
    GROUP BY cab_type
    ORDER BY pct_null DESC
""").fetchdf()

print("Payment Method null breakdown by platform:")
print(payment_dx.to_string(index=False))

print("\nFinding: Payment Method is null for ~78% of rides on BOTH platforms; not Lyft-specific.")
print("This is a dataset-level collection gap, not a platform-specific structural null.")
print("Decision → Notebook 02 (Data Cleaning): Payment analysis uses the ~22% subset where data is available,")
print("with a clear caveat that this subset may not be representative of all rides.")

"""## 9) Surge Multiplier Structure

Surge pricing is a core mechanism for both platforms. We audit its distribution and flag a notable asymmetry between Uber and Lyft.
"""

surge = con.execute("""
    SELECT
        cab_type, surge_multiplier, COUNT(*) AS rides,
        ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY cab_type), 2) AS pct_within_platform
    FROM rides_raw
    GROUP BY cab_type, surge_multiplier
    ORDER BY cab_type, surge_multiplier
""").fetchdf()

print(surge.to_string(index=False))

print("\nObservation: Uber shows surge_multiplier = 1.0 for ALL 385,663 rides.")
print("Lyft shows variation across 7 discrete levels (1.0 through 3.0).")
print("6.82% of Lyft rides occur with any surge above baseline.")
print("Decision → Notebook 03: Surge analysis scoped to Lyft only.")

"""## 10) Segment Views for Downstream Notebooks

Three persistent views registered, Data-processing and EDA will reference these directly.
"""

con.execute("CREATE OR REPLACE VIEW uber_rides AS SELECT * FROM rides_tiered WHERE cab_type = 'Uber'")
con.execute("CREATE OR REPLACE VIEW lyft_rides AS SELECT * FROM rides_tiered WHERE cab_type = 'Lyft'")
con.execute("CREATE OR REPLACE VIEW rides_priceable AS SELECT * FROM rides_tiered WHERE name != 'Taxi'")

views = con.execute("""
    SELECT table_name AS view_name
    FROM information_schema.tables
    WHERE table_schema = 'main'
    ORDER BY table_name
""").fetchdf()

print("Registered views:\n")
print(views.to_string(index=False))

"""## 11) Structuring Summary

| Dimension | Finding |
|---|---|
| **Granularity** | One row = one unique ride booking |
| **Total records** | 693,071 rows |
| **Platforms** | Uber 55.6% (n=385,663) · Lyft 44.4% (n=307,408) |
| **Coverage** | November–December 2018 · 12 Boston neighborhoods |
| **Ride tiers** | Economy · Standard · Standard-XL · Premium · Premium-XL · Accessible · Taxi |
| **Price nulls** | 55,095 rows: structural, Taxi product only (7.9%) |
| **Payment Method nulls** | 543,071 rows: both platforms equally (~78%); dataset-level collection gap |
| **Ratings nulls** | 600,071 rows: 86.6% of all rides; rated subset used for Section E analysis |
| **Surge data** | Uber: no variation captured · Lyft: 7 discrete levels (1.0–3.0), 6.82% of rides surged |
| **Avg price** | Lyft (17.35 USD) prices higher than Uber (15.80 USD)  driven by product mix, not tier-for-tier difference |
| **Route/time dupes** | 10 combinations with identical route+time+product; negligible (~0.001%), unique IDs confirm no data errors |

**Decisions carried into Notebook 02:**
- Taxi rows excluded from price analysis; flagged as separate segment
- Payment method analysis uses available ~22% subset with explicit representativeness caveat
- Surge analysis scoped to Lyft only (Uber surge not captured at row level)
- Monthly imbalance (5 Nov days vs 12 Dec days) flagged for time-series analysis
- Views `rides_tiered`, `uber_rides`, `lyft_rides`, `rides_priceable` available for reuse

"""